# Generated by Django 5.2.4 on 2025-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='slug-temporario', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
