# Generated by Django 5.2.4 on 2025-08-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postattachment',
            options={'verbose_name': 'Post Attachment', 'verbose_name_plural': 'Post Attachments'},
        ),
    ]
